#!/bin/sh
#
# @name DK_CUAVx7
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Farhang Naderi <drinkinghook@gmail.com>
#
# @board px4_fmu-v5 exclude
# @board bitcraze_crazyflie exclude
#
. ${R}etc/init.d/rc.heli_defaults

param set-default IMU_GYRO_CUTOFF 30

param set-default MC_ROLLRATE_P 0.14
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCHRATE_D 0.004

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX  0.4755
param set-default CA_ROTOR0_PY  0.1545
param set-default CA_ROTOR0_KM  0.05

param set CA_AIRFRAME 11

