/****************************************************************************
 *
 *   Copyright (c) 2019 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

#include "ManualVelocitySmoothingXY.hpp"

#include <mathlib/mathlib.h>
#include <float.h>

using namespace matrix;

void ManualVelocitySmoothingXY::reset(const Vector2f &accel, const Vector2f &vel, const Vector2f &pos)
{
	for (int i = 0; i < 2; i++) {
		_trajectory[i].reset(accel(i), vel(i), pos(i));
	}

	resetPositionLock();
}

void ManualVelocitySmoothingXY::resetPositionLock()
{
	_position_lock_active = false;
	_position_setpoint_locked(0) = NAN;
	_position_setpoint_locked(1) = NAN;
}

void ManualVelocitySmoothingXY::update(float dt, const Vector2f &velocity_target)
{
	// Update state
	updateTrajectories(dt);

	// Lock or unlock position
	// Has to be done before _updateTrajDurations()
	// 翻译：更新位置锁定状态
	//      必须在 _updateTrajDurations()之前完成
	checkPositionLock(velocity_target);

	// Update durations and sync XY
	// 翻译：更新轨迹持续时间并同步XY
	updateTrajDurations(velocity_target);
}

void ManualVelocitySmoothingXY::updateTrajectories(float dt)
{
	for (int i = 0; i < 2; ++i) {
		_trajectory[i].updateTraj(dt);

		_state.j(i) = _trajectory[i].getCurrentJerk();
		_state.a(i) = _trajectory[i].getCurrentAcceleration();
		_state.v(i) = _trajectory[i].getCurrentVelocity();
		_state.x(i) = _trajectory[i].getCurrentPosition();
	}
}

void ManualVelocitySmoothingXY::updateTrajDurations(const Vector2f &velocity_target)
{
	for (int i = 0; i < 2; ++i) {
		_trajectory[i].updateDurations(velocity_target(i));
	}

	VelocitySmoothing::timeSynchronization(_trajectory, 2);
}

void ManualVelocitySmoothingXY::checkPositionLock(const Vector2f &velocity_target)
{
	/**
	 * During a position lock -> position unlock transition, we have to make sure that the velocity setpoint
	 * is continuous. We know that the output of the position loop (part of the velocity setpoint)
	 * will suddenly become null
	 * and only the feedforward (generated by this flight task) will remain.
	 * This is why the previous input of the velocity controller
	 * is used to set current velocity of the trajectory.
	 */
	/**
	 * 翻译：在位置锁定到位置解锁的转换过程中，我们必须确保速度设定值保持连续。
	 *      我们知道位置环路的输出（速度设定值的一部分）会突然变为空，只剩下前馈（由本次飞行任务生成）。
	 * 	    这就是为什么使用速度控制器的上一个输入来设置轨迹的当前速度。
	 */
	if (_state.v.length() < 0.1f &&
	    _state.a.length() < .2f &&
	    velocity_target.length() <= FLT_EPSILON) {
		// Lock position
		_position_lock_active = true;
		_position_setpoint_locked = _state.x;

	} else {
		// Unlock position
		if (_position_lock_active) {
			// Start the trajectory at the current velocity setpoint
			// 翻译：使用速度控制器的上一个输入来设置轨迹的当前速度。
			_trajectory[0].setCurrentVelocity(_velocity_setpoint_feedback(0));
			_trajectory[1].setCurrentVelocity(_velocity_setpoint_feedback(1));
			_state.v = _velocity_setpoint_feedback;
			resetPositionLock();
		}

		_trajectory[0].setCurrentPosition(_position_estimate(0));
		_trajectory[1].setCurrentPosition(_position_estimate(1));
	}
}
